#!/bin/bash
set -euo pipefail

check_dockerfile() {
	local dockerfile=$1
	local base_image=$2
	local results=""

	echo "Checking $dockerfile..."

	packages=$(grep -oP '(?<=\s)[a-z0-9\-]+=[0-9][a-zA-Z0-9.:+~-]*' "$dockerfile" || true)

	if [ -z "$packages" ]; then
		echo "No pinned packages found in $dockerfile"
		return
	fi

	pkg_names=()
	current_versions=()

	for pkg_version in $packages; do
		pkg_names+=("$(echo "$pkg_version" | cut -d= -f1)")
		current_versions+=("$(echo "$pkg_version" | cut -d= -f2)")
	done

	echo "Found ${#pkg_names[@]} pinned packages"

	available_output=$(docker run --rm "$base_image" sh -c '
        set -e
        apt-get update -qq 2>/dev/null
        for pkg in "$@"; do
            candidate=$(
                apt-cache policy "$pkg" 2>/dev/null | \
                grep -A1 "Candidate:" | \
                tail -1 | \
                awk "{print \$2}"
            )
            echo "${candidate}"
        done
    ' sh "${pkg_names[@]}" || echo "")

	IFS=$'\n' read -r -d '' -a available_versions < <(printf '%s\0' $available_output || printf '\0')

	for idx in "${!pkg_names[@]}"; do
		pkg_name=${pkg_names[$idx]}
		current_version=${current_versions[$idx]}
		available="${available_versions[$idx]}"

		echo "Checking $pkg_name (current: $current_version)..."

		if [ -z "$available" ]; then
			results="${results}
- **$pkg_name**: Could not determine available version"
			continue
		fi

		if [ "$current_version" != "$available" ]; then
			results="${results}
- **$pkg_name**: $current_version --> $available"
			echo "  Update available: $current_version --> $available"
		else
			echo "  Up to date"
		fi
	done

	echo "$results"
}

docker build -t local-base base/

base_results=$(check_dockerfile "base/Dockerfile" "debian:13-slim")
devcontainer_results=$(check_dockerfile "devcontainer/Dockerfile" "local-base")

all_results=""
if [ -n "$base_results" ]; then
	all_results="${all_results}### base/Dockerfile
${base_results}"
fi
if [ -n "$devcontainer_results" ]; then
	all_results="${all_results}

### devcontainer/Dockerfile
${devcontainer_results}"
fi

if [ -n "$all_results" ]; then
	echo "UPDATES_FOUND=true" >variables.env
	echo "$all_results" >update_results.txt
	echo "Updates found, creating issue..."
else
	echo "UPDATES_FOUND=false" >variables.env
	echo "No updates found"
	exit 0
fi

results=$(cat update_results.txt)
checked_date=$(date -u +"%Y-%m-%dT%H:%MZ")

cat >issue.json <<'ISSUEJSON'
{
  "title": "APT Package Updates Available",
  "labels": "apt-updates,dependencies",
  "body": "# APT Package Updates Available\n\nThe following pinned APT packages have newer versions available:\n\nRESULTS_PLACEHOLDER\n\n## Action Required\n\nPlease review these updates and update the Dockerfiles accordingly. Consider:\n1. Testing the new versions in a development environment\n2. Checking for breaking changes in package changelogs\n3. Updating the pinned versions in the Dockerfiles\n4. Running build workflows to verify compatibility\n\n---\n*This issue was automatically generated by the `check-apt-updates` pipeline.*\n*Last checked: DATE_PLACEHOLDER*"
}
ISSUEJSON

sed -i "s/RESULTS_PLACEHOLDER/$results/g" issue.json
sed -i "s/DATE_PLACEHOLDER/$checked_date/g" issue.json

EXISTING=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
	"$CI_API_V4_URL/projects/$CI_PROJECT_ID/issues?state=opened&labels=apt-updates")

EXISTING_ID=$(echo "$EXISTING" | python3 -c "
import sys, json
issues = json.load(sys.stdin)
print(next((str(i['id']) for i in issues if i['title']=='APT Package Updates Available'), ''))
" 2>/dev/null || echo "")

if [ -n "$EXISTING_ID" ]; then
	echo "Updating existing issue #$EXISTING_ID"
	curl -s --request PUT \
		--header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
		--header "Content-Type: application/json" \
		--data @issue.json \
		"$CI_API_V4_URL/projects/$CI_PROJECT_ID/issues/$EXISTING_ID"
else
	echo "Creating new issue"
	curl -s --request POST \
		--header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
		--header "Content-Type: application/json" \
		--data @issue.json \
		"$CI_API_V4_URL/projects/$CI_PROJECT_ID/issues"
fi
